#!/bin/bash
set -e
set -x

BASE="$(cd $(dirname $0); pwd -P)"

VIMRC_IN=$BASE/vimrc
VIMRC_OUT=$BASE/.vimrc

START=$BASE/start

VIMPLUG=$BASE/autoload/plug.vim
PLUGGED=$BASE/plugged


echo downloading vim-plug
[ -f $VIMPLUG ] || \
    curl -sfLo $VIMPLUG --create-dirs \
        https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
mkdir -p $PLUGGED

echo preparing vimrc
echo set runtimepath+="$BASE" > "$VIMRC_OUT"
cat $VIMRC_IN/basic.vim >> "$VIMRC_OUT"
echo "call plug#begin('$PLUGGED')" >> "$VIMRC_OUT"
cat $VIMRC_IN/plug.vim >> "$VIMRC_OUT" 
echo 'call plug#end()' >> "$VIMRC_OUT"
cat $VIMRC_IN/plug-*.vim >> "$VIMRC_OUT"


echo preparing start
cat > "$START" <<EOF
#!/bin/sh
vim -u $VIMRC_OUT \$@
EOF
chmod +x $START


echo installing plugins
./start +PlugInstall +GoInstallBinaries +qall

echo completed
